namespace RadarV2.Models;

public class StudioProject
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string TemplateId { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string UserId { get; set; } = string.Empty;
    public bool IsCompleted { get; set; }
    public bool IsPublic { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// AI-generated execution plan, built on demand from the project plus the user's profile and
    /// persisted so it stays stable across sessions. Null until the user asks for one.
    /// </summary>
    public ProjectPlan? Plan { get; set; }
}

/// <summary>
/// A concrete way to actually finish a Studio project: what to produce, in what order, and how the
/// user will know it is done. Generated by the shared AI engine, with a deterministic fallback.
/// </summary>
public class ProjectPlan
{
    public string Summary { get; set; } = string.Empty;
    public List<ProjectMilestone> Milestones { get; set; } = [];
    public List<string> Deliverables { get; set; } = [];
    public string? SuccessCriteria { get; set; }
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
}

public class ProjectMilestone
{
    public string Title { get; set; } = string.Empty;
    public string Outcome { get; set; } = string.Empty;
    public string EstimatedTime { get; set; } = string.Empty;
    public List<string> Steps { get; set; } = [];
    public bool IsComplete { get; set; }
}

public class ProjectTemplate
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public string EstimatedTime { get; set; } = string.Empty;
    public List<string> Tags { get; set; } = [];
}
